#lang scheme
(define (square n)
  (* n n))
(define (square-list items)
    (if (null? items)
        '()
        (cons (square (car items))
              (square-list (cdr items)))))
(define (square-list1 items)
    (map square items))
(square-list (list 1 2 3 4))