#lang racket
(define (* a b)
  (cond ((= b 0) 0)
        ((= b 1) a)
        ((even? b) (double (* a (halve b))))
        (else (+ a (double (* a (halve (- b 1))))))
))
(define (double x)
  (+ x x))
(define (halve x)
  (/ x 2))
(* 3 6)