(define tolerance 0.00001)
(define (fixed-point f first-guess)
	(define (close-enough? v1 v2)
		(< (abs (- v1 v2)) tolerance))
	(define (output guess cnt)
		 (display guess)
		 (display "****")
		 (display cnt))
	(define (try guess cnt)
		(let ((next (f guess)))
			(if (close-enough? guess next)
			 (output guess cnt)
			 (try next (+ cnt 1)))))
	(try first-guess 0))

(define (f x) (/ (log 1000) (log x)))
(define (g x) (/ (+ x (f x)) 2))
(fixed-point f 2.0)
(fixed-point g 2.0)
