(define (cons a b)
    (lambda (m) (m a b)))
(define (car z)
    (z (lambda (p q) (fast-exp p 2))))
(define (cdr z)
    (z (lambda (p q) (fast-exp q 3))))
(define (fast-exp n b)
    (cond ((= n 0) 1)
          ((even? n) (square (fast-exp (/ n 2) b)))
          (else (* b (fast-exp (- n 1) b)))))
(define (square n) (* n n))
