(define (mul a b)
  (mmul a b 0))
(define (mmul a b n)
  (cond ((= b 0)
		 n)
		((even? b)
		 (mmul (double a) (half b) n))
		(else (mmul a (- b 1) (+ n a)))))
(define (even? n)
  (= (remainder n 2) 0))
(define (double n)
  (+ n n))
(define (half n)
  (/ n  2))
